branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  # - "@semantic-release/npm"  # optional if you publish to npm
  - 
    - "@semantic-release/exec"
    - 
      prepareCmd: |
        npm version ${nextRelease.version} --no-git-tag-version
        sed -i '' "s/.version(\"[^\"]*\")/.version(\"${nextRelease.version}\")/" assets/ts/cli.ts
  - 
    - "@semantic-release/git"
    - 
      assets:
        - package.json
        - package-lock.json  # if you have one
        - CHANGELOG.md
        - assets/ts/cli.ts
      message: "chore(release): $$ {nextRelease.version} [skip ci]\n\n $${nextRelease.notes}"